export default async function handler(req,res){
  res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Methods","GET,POST,PUT,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type,Authorization");
  if(req.method==="OPTIONS")return res.status(200).end();
  const CI=process.env.ML_CLIENT_ID,CS=process.env.ML_CLIENT_SECRET,RU=process.env.ML_REDIRECT_URI;
  const{action}=req.query;const body=req.body||{};
  async function ml(path,m="GET",data=null,t){const o={method:m,headers:{"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})}};if(data)o.body=JSON.stringify(data);return(await fetch(`https://api.mercadolibre.com${path}`,o)).json();}
  try{
    if(action==="auth"){const r=await fetch("https://api.mercadolibre.com/oauth/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"authorization_code",client_id:CI,client_secret:CS,code:body.code,redirect_uri:RU})});const d=await r.json();if(d.access_token)return res.json({ok:true,token:d.access_token,refresh:d.refresh_token,expires:d.expires_in});return res.status(400).json({ok:false,error:d.message});}
    if(action==="refresh"){const r=await fetch("https://api.mercadolibre.com/oauth/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",client_id:CI,client_secret:CS,refresh_token:body.refresh_token})});const d=await r.json();if(d.access_token)return res.json({ok:true,token:d.access_token,refresh:d.refresh_token,expires:d.expires_in});return res.status(400).json({ok:false,error:d.message});}
    if(action==="account"){const d=await ml("/users/me","GET",null,body.token);if(d.id)return res.json({ok:true,account:{id:d.id,name:d.nickname,email:d.email}});return res.status(400).json({ok:false,error:"Token inválido"});}
    if(action==="items"){const{token,userId}=body;const s=await ml(`/users/${userId}/items/search?status=active&limit=50`,"GET",null,token);if(!s.results)return res.json({ok:true,items:[]});const ids=s.results.slice(0,20).join(",");const d=await ml(`/items?ids=${ids}`,"GET",null,token);const items=(d||[]).map(i=>({id:i.body?.id,title:i.body?.title,price:i.body?.price,status:i.body?.status,thumbnail:i.body?.thumbnail,hasVideo:!!i.body?.video_id})).filter(i=>i.id);return res.json({ok:true,items});}
    if(action==="validate"){const ext=body.videoUrl?.split(".").pop()?.toLowerCase();return res.json({ok:true,checks:[{check:"Formato MP4",ok:ext==="mp4",msg:ext==="mp4"?"✅ MP4 detectado":"⚠️ Verifique se é MP4"},{check:"Resolução",ok:null,msg:"⚠️ Mínimo 720p"},{check:"Duração",ok:null,msg:"⚠️ Entre 5s e 5min"},{check:"Tamanho",ok:null,msg:"⚠️ Máx 500MB"}],requirements:{format:"MP4",minDuration:"5s",maxDuration:"5min",minResolution:"720p",maxSize:"500MB"}});}
    if(action==="upload"){const{token,videoUrl,itemId}=body;if(!token||!videoUrl||!itemId)return res.status(400).json({ok:false,error:"token, videoUrl e itemId obrigatórios"});const d=await ml(`/items/${itemId}/video`,"PUT",{video_url:videoUrl},token);if(d.status==="active"||d.video_id)return res.json({ok:true,status:"completed",videoId:d.video_id||d.id});if(d.status===403||d.error==="forbidden")return res.json({ok:false,status:"unavailable",message:"Função não disponível pela API oficial do Mercado Livre."});return res.json({ok:false,status:"failed",error:d.message||"Erro ao enviar vídeo"});}
    return res.status(400).json({ok:false,error:`Ação desconhecida: ${action}`});
  }catch(e){return res.status(500).json({ok:false,error:e.message});}
}