export default async function handler(req,res){
  res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type");
  if(req.method==="OPTIONS")return res.status(200).end();
  const CI=process.env.YOUTUBE_CLIENT_ID,CS=process.env.YOUTUBE_CLIENT_SECRET;
  const RU=process.env.YOUTUBE_REDIRECT_URI||`${process.env.APP_URL}/api/youtube-publish?action=callback`;
  const{action}=req.query;const body=req.body||{};
  try{
    if(action==="auth-url"){if(!CI)return res.json({ok:false,error:"YOUTUBE_CLIENT_ID não configurado no Vercel"});const sc=encodeURIComponent("https://www.googleapis.com/auth/youtube.upload https://www.googleapis.com/auth/youtube");return res.json({ok:true,url:`https://accounts.google.com/o/oauth2/v2/auth?client_id=${CI}&redirect_uri=${encodeURIComponent(RU)}&response_type=code&scope=${sc}&access_type=offline&prompt=consent`});}
    if(action==="callback"){const{code}=req.query;if(!code)return res.redirect(`/?yt_error=no_code`);const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:CI,client_secret:CS,redirect_uri:RU,grant_type:"authorization_code"})});const d=await r.json();if(d.access_token){const p=new URLSearchParams({yt_token:d.access_token,yt_refresh:d.refresh_token||"",yt_expires:String(Date.now()+(d.expires_in||3600)*1000)});return res.redirect(`/?${p.toString()}`);}return res.redirect(`/?yt_error=${encodeURIComponent(d.error||"auth_failed")}`);}
    if(action==="refresh"){const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({refresh_token:body.refresh_token,client_id:CI,client_secret:CS,grant_type:"refresh_token"})});const d=await r.json();if(d.access_token)return res.json({ok:true,token:d.access_token,expires:Date.now()+(d.expires_in||3600)*1000});return res.json({ok:false,error:d.error||"Falha ao renovar token"});}
    if(action==="channel"){const r=await fetch("https://www.googleapis.com/youtube/v3/channels?part=snippet,statistics&mine=true",{headers:{Authorization:`Bearer ${body.token}`}});const d=await r.json();const ch=d.items?.[0];if(ch)return res.json({ok:true,channel:{id:ch.id,name:ch.snippet.title,thumb:ch.snippet.thumbnails?.default?.url,subs:ch.statistics?.subscriberCount}});return res.json({ok:false,error:"Canal não encontrado"});}
    if(action==="upload"){const{token,videoUrl,title,description,tags,privacy,scheduledAt}=body;if(!token)return res.json({ok:false,error:"Token não fornecido."});if(!videoUrl)return res.json({ok:false,error:"URL do vídeo obrigatória"});const vr=await fetch(videoUrl);if(!vr.ok)return res.json({ok:false,error:"Não foi possível baixar o vídeo"});const vb=await vr.arrayBuffer();const ct=vr.headers.get("content-type")||"video/mp4";const mr=await fetch("https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json","X-Upload-Content-Type":ct,"X-Upload-Content-Length":String(vb.byteLength)},body:JSON.stringify({snippet:{title:title||"Vídeo AfiliadoAI",description:description||"",tags:tags||["afiliado","oferta"],categoryId:"22"},status:{privacyStatus:scheduledAt?"private":(privacy||"public"),...(scheduledAt?{publishAt:new Date(scheduledAt).toISOString()}:{}),selfDeclaredMadeForKids:false}})});const uu=mr.headers.get("location");if(!uu){const e=await mr.json();return res.json({ok:false,error:e.error?.message||"Falha ao iniciar upload"});}const ur=await fetch(uu,{method:"PUT",headers:{"Content-Type":ct,"Content-Length":String(vb.byteLength)},body:vb});const ud=await ur.json();if(ud.id)return res.json({ok:true,videoId:ud.id,url:`https://www.youtube.com/watch?v=${ud.id}`,status:ud.status?.uploadStatus,scheduled:scheduledAt||null});return res.json({ok:false,error:ud.error?.message||"Falha no upload"});}
    return res.json({ok:false,error:`Ação desconhecida: ${action}`});
  }catch(e){return res.status(500).json({ok:false,error:e.message});}
}